default_context:
  project_name: "example"
  project_slug: "example"
  domain_main: "example.com"
  domain_staging: "stag.example.com"
  docker_swarm_stack_name_main: "example-com"
  docker_swarm_stack_name_staging: "stag-example-com"
  secret_key: "a9bbbbb76930884ce17ec728e734397dd3217aea19dca2fa9488d31054fbf213"
  first_superuser: "admin@example.com"
  first_superuser_password: "admin"
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.example.com", "https://stag.example.com", "https://example.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: "587"
  smtp_host: ""
  smtp_user: ""
  smtp_password: ""
  smtp_emails_from_email: "info@example.com"
  postgres_password: "admin"
  pgadmin_default_user: "admin@example.com"
  pgadmin_default_user_password: "admin"
  traefik_constraint_tag: "example.com"
  traefik_constraint_tag_staging: "stag.example.com"
  traefik_public_constraint_tag: "traefik-public"
  flower_auth: "admin:admin"
  sentry_dsn: ""
  docker_image_prefix: ""
  docker_image_backend: "backend"
  docker_image_celeryworker: "celeryworker"
